### PR TITLE
Created a first draft of Gordon's vital stats file

### PR DESCRIPTION
**Pull request by gchadwick10**
Some new information for Gordon's vital stats file.

### CODE REVIEW

**Comment by famousfolly** [comment]
👍

**Comment by byFives** [comment]
Leaving a witty yet humorously impactful comment here.

**Comment by byFives** [comment]
🐳

**Comment by byFives** [comment]
@jdmar3 ☎️ ✉️ 💥

**Comment by famousfolly** [comment]
@jdmar3 ready to merge! 😄

**Pull request merged**
